bgs/urls.py
"""
    Master URL routing for the bgs project
    bgs / urls.py
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
"""
    URL routing for the main_app
    main_app / urls.py
"""
from functools import partial

from django.urls import path
from . import views

urlpatterns: list[partial] = [

    # landing page
    path("", views.index.home, name="home"),

    # games
    path("games/", views.games.index, name="games_index"),
    path("games/create/", views.games.create, name="games_create"),
    path("games/<int:pk>/update/", views.games.update, name="games_update"),
    path("games/<int:pk>/", views.games.detail, name="games_detail"), # TODO: refactor to games/<str:username>/<str:game_title>/
    path("games/<int:pk>/delete/", views.games.delete, name="games_delete"),
    path("games/<int:pk>/delete/files/", views.games.delete_files, name="games_delete_files"),
    # game reviews/comments
    path("games/<int:game_id>/add_review/", views.reviews.add_review, name="add_review"),
    path("reviews/<int:review_id>/edit/", views.reviews.edit_review, name="edit_review"),
    path("reviews/<int:review_id>/delete/", views.reviews.delete_review, name="delete_review"),

    # favorites
    path("favorites/add/<int:game_id>/<int:user_id>/", views.api.favorite.add, name="favorite_add"),
    path("favorites/remove/<int:game_id>/<int:user_id>/", views.api.favorite.remove, name="favorite_remove"),
    path("favorites/count/game/<int:game_id>/", views.api.favorite.game_favorite_count, name="game_favorite_count"),
    path("favorites/exists/game/<int:game_id>/", views.api.favorite.exists, name="favorite_exists"),

    # game screenshot
    path('games/<int:game_id>/add_screenshot/', views.screenshots.create, name="screenshots_add"),

    # profile
    path("profile/", views.profile.index, name="profile_index"),
    path("profile/<str:username>/", views.profile.profile, name="profile_public"),
    path("profile/update/", views.profile.update, name="profile_update"),
    path("profile/delete/", views.profile.delete, name="profile_delete"),

    # registration
    path("accounts/signup/", views.accounts.signup, name="signup"),

    # api
    # - color-mode
    path("api/color-mode/<str:mode>/", views.api.color_mode.set, name="profile_color_mode_set"),
    path("api/color-mode/", views.api.color_mode.get, name="profile_color_mode_get"),
    # - search
    path("api/search/games/", views.api.search.search_games, name="search_games"),
    path("api/search/top-tags/", views.api.search.top_tags, name="search_top_tags"),

]

main_app/models/Favorite.py
from django.contrib.auth.models import User
from django.db import models

class Favorite(models.Model):
    game = models.ForeignKey("Game", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main_app/models/Game.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from .Tag import Tag
from ..util.s3 import get_base_url, get_bucket_name


class Game(models.Model):
    """
        A model representing user-uploaded games
    """

    # ===== fields ============================================================

    title = models.CharField(max_length=128, default="")
    """
        displayable name of the game
    """


    description = models.TextField(default="")
    """
        game description 
    """


    tags = models.ManyToManyField(Tag)
    """
        list of tags to be used for search purposes
    """


    times_viewed = models.IntegerField(default=0)
    """
        number of times a visitor has viewed the game's page
        TODO: Move this to a metrics model?
    """


    is_published = models.BooleanField(default=False)
    """
        whether user has published this game for public viewing
    """


    frame_width = models.IntegerField(default=640)
    """
        width of the iframe, a value of -1 will use the entire view width
    """


    frame_height = models.IntegerField(default=480)
    """
        height of the iframe, a value of -1 will use the entire view height
    """

    add_fullscreen_btn = models.BooleanField(default=True)
    """
        whether to add a fullscreen button
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    """
        creator of the game
    """


    created_at = models.DateTimeField(default=timezone.now)


    updated_at = models.DateTimeField(default=None, blank=True, null=True)


    # ===== functions =========================================================

    def url(self):
        return f"{get_base_url()}{get_bucket_name()}/user/{self.user_id}/games/{self.id}/files/index.html"

    def save(self):
        self.updated_at = timezone.now()

        return super().save()

    def __repr__(self) -> str:
        """human-readable string representation"""
        return f"{self.title} by {self.user.username}"

    def __str__(self) -> str:
        return self.__repr__()

main_app/models/Screenshot.py
from django.db import models
from django.utils import timezone

from .File import File
from .Game import Game


class Screenshot(models.Model):
    """
        Model representing a screenshot image file for a game
    """

    # ===== metadata ==========================================================



    class Meta:
        ordering = ["created_on"]
        """
            Order by date created.
            Icebox feature: allow user to choose the Screenshot ordering 
        """


    # ===== fields ============================================================


    file = models.OneToOneField(File, on_delete=models.DO_NOTHING, null=True)
    """
        The associated image File
        Relationship: Screenshot ---- File

        on_delete:
        When the Screenshot is deleted, we also want to delete its
        corresponding File. `on_delete` is set to `DO_NOTHING`, because there
        is no built-in method for the child to delete its parent on_delete.
        So the desired behavior is manually executed in `Screenshot.delete`.
    """

    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    """
        The associated Game that owns this Screenshot
        Relationship: Screenshot >--- Game
    """


    created_on = models.DateTimeField(default=timezone.now)


    # ===== functions =========================================================


    def delete(self, *args, **kwargs):
        """Clean up File when screenshot is deleted"""
        file = self.file

        self.file = None
        self.save()
        file.delete()

        # perform inherited delete
        return super(self.__class__, self).delete(*args, **kwargs)


    def __repr__(self) -> str:
        """Human-readable string representation"""
        return f"for {self.game.title} @{self.file.filename}"


    def __str__(self) -> str:
        return self.__repr__()

main_app/models/Tag.py
from django.db import models

class Tag(models.Model):
    """
        Hashtag for searching for games
    """

    # ===== fields ============================================================


    text = models.CharField(64)


    # ===== functions =========================================================


    def __repr__(self):
        return f"#{self.text}"

    def __str__(self):
        return self.__repr__()

main_app/forms.py
"""
    Custom forms for main_app
"""
from django.core.exceptions import ValidationError
from django.db.models import QuerySet
from django import forms

from .models import Game, Tag


class TagsField(forms.CharField):
    def to_python(self, value: str) -> QuerySet:
        """Normalize data to a QuerySet of Tag models,
        Create Tags if it doesn't exist"""

        # return an empty QuerySet if there is no tag data
        if not value or not value.strip():
            return Tag.objects.none()

        # parse strings into Tags
        #    the implementation on the frontend separates tags with "\xa0",
        #    which is just a non-linebreaking space.
        tag_strs = [val.strip() for val in value.split("\xa0")]
        tag_ids = []
        for tag_str in tag_strs:
            # don't parse blank tags from any trailing spaces
            if not tag_str: continue

            # create tags
            new_tag = Tag.objects.get_or_create(text=tag_str)
            tag_ids.append(new_tag[0].id)

        # return a query with all tags
        return Tag.objects.filter(id__in=tag_ids)

    def validate(self, value):
        """Make sure valid tag instances were received"""
        super().validate(value)
        if not isinstance(value, QuerySet):
            raise ValidationError("Invalid value: %(value)",
                                  params={"value": value})

    def clean(self, value):
        res = self.to_python(value)
        self.validate(res)
        return res



class GameForm(forms.ModelForm):
    game = forms.FileField(widget=forms.FileInput(attrs={"accept": ".zip"}))
    tags = TagsField(required=False) #ArrayField(CharField(), size=4)
    class Meta:
        model = Game
        fields = ["title", "description", "tags", "frame_width", "frame_height"]

main_app/forms/GameCreateForm.py
from django.forms import forms, widgets

from .GameForm import GameForm

class GameCreateForm(GameForm):
    """
        Form to edit games
    """
    zip_upload = forms.FileField(widget=widgets.FileInput(attrs={"accept": ".zip"}), required=True)

main_app/forms/GameEditForm.py
from .GameForm import GameForm

from django.forms import forms, widgets

class GameEditForm(GameForm):
    """
        Form to edit games
    """
    zip_upload = forms.FileField(widget=widgets.FileInput(attrs={"accept": ".zip"}), required=False)

main_app/forms/GameForm.py
from django import forms

from django.forms import FileField, CharField, Textarea

from ..models import Game
from .fields import TagsField
from .fields import CheckboxField


class GameForm(forms.ModelForm):
    """
        Form to edit games
    """

    description = CharField(widget=Textarea(attrs={"rows": "10"}), required=False)

    tags = TagsField(required=False)
    tags.widget.attrs.update({"placholder": "no tags"})

    add_fullscreen_btn = CheckboxField(label="Add fullscreen button?", required=False)
    is_published = CheckboxField(label="Publish", required=False)

    screenshot = FileField(required=False)


    class Meta:
        model = Game
        fields = ["title", "description", "tags", "frame_width", "frame_height",
                  "add_fullscreen_btn", "is_published"]

main_app/forms/ProfileForm.py
from django import forms
from django.contrib.postgres.forms import SimpleArrayField

class ProfileForm(forms.Form):
    """
        Form to update a profile
    """

    username = forms.CharField()
    """
        User's username, used to log-in
        Must be unique. Required.
    """


    display_name = forms.CharField()
    """
        Outward facing name that will appear on profile, reviews, etc.
        Required.
    """


    email = forms.EmailField()
    """
        User's email address for validation, notifications, etc.
        Must be unique. Required.
    """


    password = forms.PasswordInput()
    """
        User's password for log-in validation.
        Optional. Leave blank to keep old password.
    """


    confirm_password = forms.PasswordInput()
    """
        Confirm password, must match with password to validate successfully.  
    """


    avatar = forms.FileField(label="Profile picture", required=False)
    """
        Set when the user wants to override their current avatar image.
    """


    bio = forms.CharField(widget=forms.Textarea, required=False)
    """
        Text area for user bio / about me.
    """


    social_links = SimpleArrayField(forms.URLField(), required=False)
    """
        List of social links.
    """

main_app/views.py
"""
    View functions
    main_app / views.py
"""
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

def home(request: HttpRequest):
    """
        Displays main home landing page
        Routing: ""
        Name: "home"
    """
    return render(request, "home.html")

def games_index(request: HttpRequest):
    """
        Displays the games listing page
        Routing: "games/"
        Name: "games_index"
    """
    return render(request, "games/index.html")

main_app/views/accounts.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from ..models import Profile


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

def signup(request):
    error_message = ""
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user: User = form.save()
            user.profile = Profile(user=user, display_name=user.username)
            user.profile.save()
            user.save()
            login(request, user)
            return redirect("profile_index")
        else: 
            error_message = "Invalid sign up - try again"
    else:
        form = SignupForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)

main_app/views/index.py
"""
    View functions for webroot
    main_app / views / index.py

    home - displays landing page
"""

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404


def home(request: HttpRequest):
    """
        Displays main home landing page
        Routing: ""
        Name: "home"
    """
    return render(request, "home.html")

main_app/views/profile.py
"""
    View functions for Profile model
    main_app / views / profile.py

    index - redirects to the logged-in user's profile

    profile - displays user profile

    update - handles both display of update form (GET),
        and update form handling (POST)

    delete - deletes profile
"""
from pathlib import PurePath

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.files.uploadedfile import UploadedFile
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from ..forms import ProfileForm
from ..models import File


@login_required
def index(request: HttpRequest) -> HttpResponse:
    """
        Serves as a log-in redirect route -> goes to the user's page

        url:   profile/
        name: "profile_index"
    """
    return redirect("profile_public", username=request.user.username)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    """
        Displays a user's public profile, includes editing utilities if owner is logged in.

        url:   profile/<str:username>/
        name: "profile_public"
    """

    target_user = get_object_or_404(User, username=username)
    return render(request, "profile/index.html", {
        "target_user": target_user
    })


@login_required
def update(request: HttpRequest) -> HttpResponse:
    """
        Handles both Profile form display on "GET", and submission on "POST"

        url:  profile/<int:pk>/update/
        name: "profile_update"
    """

    if request.method == "GET":     # display profile update form

        form = ProfileForm()
        return render(request, "profile/form.html", {
            "form": form
        })

    elif request.method == "POST":  # handle profile update form submission

        # populate form
        form = ProfileForm(request.POST, files=request.FILES)

        # check for validity
        is_valid = form.is_valid()

        if is_valid:
            # if password was updated
            if request.POST["password"]:
                # password & confirm_password must match
                is_valid = request.POST["password"] == request.POST["confirm_password"]

        if is_valid:
            user = request.user
            prof = user.profile

            # update user-related fields
            user.username = request.POST["username"]
            user.email = request.POST["email"]

            if request.POST["password"]:
                user.password = request.POST["password"]

            # update profile-related fields
            prof.display_name = request.POST["display_name"]

            avatar_file: UploadedFile = request.FILES.get("avatar", None)

            if avatar_file:

                # create and upload avatar
                avatar = File.helpers.create_and_upload(avatar_file,
                 f"user/{str(user.id)}/profile/avatar{PurePath(avatar_file.name).suffix}")

                if avatar:

                    # delete any pre-existing avatar
                    if prof.avatar:
                        prof.avatar.delete()

                    # set the avatar
                    prof.avatar = avatar

                else:
                    # avatar failed to upload/create
                    print("view profile/update error: failed to upload avatar")

            prof.bio = request.POST["bio"]
            prof.social_links = request.POST["social_links"]

            # done, commit changes
            user.save()
            prof.save()

        return redirect("profile_index")


@login_required
def delete(request: HttpRequest, pk: int) -> HttpResponse:
    """
        TODO: implement
    """
    pass

main_app/templates/games/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        iframe {
            display: block;
            margin: auto auto;
            z-index: 999;

            border-radius: 2px;

            overflow: hidden;
        }

        iframe.fullscreen {
            margin: 0;
            padding: 0;
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;

            border-radius: 0;
            box-shadow: unset;

            overflow: auto;
        }

        #fullscreen-btn {
            opacity: .5;
            border-radius: 15%;
            background-color: #f3f3f3;
            transition: opacity .15s linear;
        }

        #fullscreen-btn:hover {
            opacity: 1;
        }

        #fullscreen-btn.fullscreen {
            position: fixed;
            bottom: 1vmin;
            right: 1vmin;
            z-index: 9999;
        }

        .screenshot-container {
            aspect-ratio: 8/1;
            width: 100%;
        }

        #container {
            max-width: 1000px;
        }

        #reviews-accordion {
            border-radius: 4px;
            padding: 4px;
        }

        .accordion-button, .accordion-item {
            background-color: transparent !important;
            border: 0 !important;
        }

        .tag, .author {
            text-decoration: none;
        }

        .tag-text:hover, .author:hover {
            text-decoration: underline;
        }
    </style>



    <div id="container" class="mt-4 container-fluid">

        <article class="card bg-transparent shadow-lg border-0 mb-5">

{#            {% if game.screenshot_set.count %}#}
{#                <div class="screenshot-container card-header p-0 overflow-hidden">#}
{#                        <img src="{{ game.screenshot_set.first.file.url }}" class="object-fit-cover w-100 h-100" alt="screenshot of game">#}
{#                </div>#}
{#            {% endif %}#}


            {# display game window #}
            <div class="card-body overflow-auto pt-5">
                <iframe class="shadow-sm" allowtransparency="false" loading="lazy" width="{{ game.frame_width }}" height="{{ game.frame_height }}" src="{{ game.url }}"></iframe>
                {% if game.add_fullscreen_btn %}
                    <button class="float-end btn btn-light" id="fullscreen-btn"><i class="bi bi-fullscreen"></i></button>
                {% endif %}
            </div>


            <div class="card-footer p-3">
                {# favorites #}
                <span class="float-end text-secondary position-relative">
                    <i id="fave-btn" class="bi {% if is_faved %}bi-heart-fill{% else %}bi-heart{% endif %} me-1"></i>
                    <span id="fave-count">{{ game.favorite_set.count }}</span>
                </span>

                {# views #}
                <span class="text-secondary float-end me-2">{{ game.times_viewed }} views</span>



                {# hashtags #}
                <p class="text-tiny mt-1">

                    {% for tag in game.tags.all %}

                        {# if any hash tags #}
                        <span class="rounded bg-secondary-subtle bg-opacity-50 p-1 me-1 shadow-sm">
                            <a class="tag text-secondary-emphasis"
                               href="{% url 'games_index' %}?q={{ tag.text }}">
                                    <span class="hash">#</span>
                                    <span class="tag-text">{{ tag.text }}</span>
                            </a>
                        </span>

                    {% empty %}

                        {# no hashtags #}
                        <span class="p-1">Tags: none</span>

                    {% endfor %}
                </p>


                {# display title #}
                <h3 class="card-title d-flex justify-content-between">
                    <a class="nav-link" href="{% url 'games_detail' game.id %}">{{ game.title }}</a>
                    {% if user.id == game.user_id or user.is_superuser %}
                        <a href="{% url 'games_update' game.id %}" class="button btn btn-outline-secondary">EDIT <i class="ms-1 bi bi-pencil"></i> </a>
                    {% endif %}
                </h3>


                {# display creator #}
                <p class="ms-1 mb-3">
                    <strong>by
                        <a class="text-secondary-emphasis text-decoration-none"
                           href="{% url 'profile_public' game.user.username %}">
                            <i class="author">{{ game.user.username }}</i>
                        </a>
                    </strong>
                </p>


                {# description #}
                {% if game.description %}
                    <p class="card ms-2 me-2 p-4 bg-transparent shadow-lg border-0" style="line-height:18px; white-space:pre-wrap;overflow-x:auto;width:100%;">{{ game.description }}</p>
                {% endif %}
            </div>

        </article>


    <div class="accordion shadow-lg" id="reviews-accordion">
        <div class="accordion-item">
            <h5 class="accordion-header">
                <button class="position-relative accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#reviews-collapse" aria-expanded="false">
                    Comments
                </button>
            </h5>
            <div id="reviews-collapse" class="container accordion-collapse collapse" data-bs-parent="#reviews-accordion">
                {% include "review/reviews.html" %}
            </div>
        </div>
    </div>


</div>

{% if game.add_fullscreen_btn %}
    <script src="{% static 'js/fullscreenToggle.js' %}"></script>
{% endif %}

{% if user.is_authenticated %}
<script>
    // Makes fave button interactive
    window.addEventListener("load", () => {
        const faveBtn = document.getElementById("fave-btn");
        const faveCount = document.getElementById("fave-count");

        faveBtn.addEventListener("click", async e => {
            if (faveBtn.classList.contains("bi-heart")) {
                faveBtn.classList.remove("bi-heart");
                faveBtn.classList.add("bi-heart-fill");
                await fetch("{% url 'favorite_add' game.id user.id %}")
            } else {
                faveBtn.classList.remove("bi-heart-fill");
                faveBtn.classList.add("bi-heart");
                await fetch("{% url 'favorite_remove' game.id user.id %}")
            }

            const res = await fetch("{% url 'game_favorite_count' game.id %}")
            const json = await res.json();
            const count = json["count"];

            // only update the count if there was no error
            if (count !== undefined) {
                faveCount.innerText = String(count);
            }
        });
    });
</script>
{% endif %}

{% endblock %}

main_app/templates/games/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <script>
        let tags = "";
        {% for tag in game.tags.all %}
            tags += "{{ tag.text }}\xa0";
        {% endfor %}
        window["game-tags"] = tags;
    </script>
    {{ form.media }}

    <section class="container">

        {% if errors %}
            <p class="errors">
                {% autoescape off %}
                    {{ errors }}
                {% endautoescape %}
            </p>
        {% endif %}

        {% if game %}
            <h1 class="mt-4 mb-4">Edit <span class="text-success">{{ game.title }}</span></h1>
        {% else %}
            <h1 class="mt-4 mb-4">Upload Game</h1>
        {% endif %}
        <div class="container">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Submit</button>

                {% if game %}
                    <button type="button" class="btn btn-outline-danger float-end mt-3" data-bs-toggle="modal" data-bs-target="#delete-modal">
                        Delete
                    </button>
                {% endif %}
            </form>
        </div>

    {% if game %}
        {# delete modal #}
        <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            Confirm deletion
                        </h5>
                        <button class="btn" type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true"><i class="bi bi-x-lg"></i></span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete <span class="text-primary">{{ game.title }}</span>?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                        <form action="{% url 'games_delete' game.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}


    </section>

    <script>
        label = document.querySelector("label[for='id_add_fullscreen_btn']");
        label.classList.add("form-check-label");

        document.querySelectorAll("textarea, input").forEach(input => {
            if (input.getAttribute("type") !== "checkbox") {
                input.classList.add("form-control");
            }
        });

    </script>


{% endblock %}

main_app/templates/games/unavailable.html
{% extends 'base.html' %}
{% block content %}

<h3 class="text-center mt-4">Error 404</h3>
<p class="text-center mt-4">Sorry, this game does not exist or is not available...</p>
<div class="d-flex flex-column align-items-center mt-4">
    <h1><i class="bi bi-controller"></i></h1>
    <a href="{% url 'games_index' %}">Return to Games</a>
</div>

{% endblock %}